### ISSUE TITLE
Do you have a friendly source code?

### ISSUE THREAD

**Issue by xdmdtz123** [ASchidler/decision_tree#1]
Dear professor:
  I’ve been reading your paper "SAT-based Decision Tree Learning for Large Data Sets" at AAAI'21. It gave me a lot of inspiration and made me Enlightened. So I want to read your source code at https://doi.org/10.5281/zenodo.4575724. But when I downloaded it, I found that there was no readme to guide me to run and read it, so I'm asking for your help.
  I'm looking forward to your reply.

**Comment by ASchidler** [comment]
Hello,

Thank you for the interest. At the moment the version you can find in the repository is available, with a short README to get started. Feel free to contact me with any specific questions/problems.

Unfortuantely, the code is designed in a way to support our experiment and is not yet very usable outside these experiments. We are currently working on a new version that is geared toward usability and is probably finished in a few weeks.
